#!/usr/bin/env bash

# From C:\Qt\5.2.1\msvc2010\bin\qtenv2.bat
PATH="/c/Qt/5.2.1/msvc2010/bin:$PATH"

# VS 2010 command line variables
source ./vcvars2010

QMAKE="/c/Qt/5.2.1/msvc2010/bin/qmake.exe"
JOM="/c/Qt/Tools/QtCreator/bin/jom.exe"
SOURCE="/c/Users/LALIC/Documents/Qt/RsaToolbox/Source/Source.pro"
BUILDDIR="/c/Users/LALIC/Documents/Qt/RsaToolbox/_build/Source"

if [ ! -d $BUILDDIR ]; then
  mkdir $BUILDDIR
fi
if [ ! -d $BUILDDIR ]; then
  echo Could not create build dir \"$BUILDDIR\"
  exit 1
fi
cd $BUILDDIR

$QMAKE $SOURCE -spec win32-msvc2010 "CONFIG+=debug" "CONFIG+=qml_debug"
$JOM qmake_all
$JOM -f Makefile.Debug all
$JOM -f Makefile.Release all
