#!/usr/bin/env bash

# Visual Studio 2010 Command Line => bash
#   Adapted from:
#   C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat

export VS100COMNTOOLS="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools"
export WindowsSdkDir="C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\"
export VSINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\"
export VCINSTALLDIR="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\"
export FrameworkDir32="C:\\Windows\\Microsoft.NET\\Framework\\"
export FrameworkVersion32="v4.0.30319"
export Framework35Version="v3.5"
export FrameworkDir=$FrameworkDir32
export FrameworkVersion=$FrameworkVersion32
export PATH="/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/IDE:/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/BIN:/c/Program Files (x86)/Microsoft Visual Studio 10.0/Common7/Tools:/c/Windows/Microsoft.NET/Framework/v4.0.30319:/c/Windows/Microsoft.NET/Framework/v3.5:/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/VCPackages:/c/Program Files (x86)/HTML Help Workshop:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin/NETFX 4.0 Tools:/c/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/bin:$PATH"
export INCLUDE="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\INCLUDE;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\include;"
export LIB="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\lib;"
export DevEnvDir="C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\IDE\\"
export LIBPATH="/c/Windows\Microsoft.NET\Framework\v4.0.30319;/c/Windows\Microsoft.NET\Framework\v3.5;/c/Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;"
